repos:
- repo: local
  hooks:
  - id: isort
    name: isort
    stages: [commit]
    language: system
    entry: bash -c 'cd daemon && poetry run isort --atomic -y'
    types: [python]

  - id: black
    name: black
    stages: [commit]
    language: system
    entry: bash -c 'cd daemon && poetry run black --exclude ".+_pb2.*.py|doc|build" .'
    types: [python]

  - id: flake8
    name: flake8
    stages: [commit]
    language: system
    entry: bash -c 'cd daemon && poetry run flake8'
    types: [python]
