[tool.poetry]
name = "core"
version = "6.6.0"
description = "CORE Common Open Research Emulator"
authors = ["Boeing Research and Technology"]
license = "BSD-2-Clause"
repository = "https://github.com/coreemu/core"
documentation = "https://coreemu.github.io/core/"
include = ["core/gui/data/**/*", "core/configservices/*/templates"]

[tool.poetry.dependencies]
python = "^3.6"
dataclasses = { version = "*", python = "3.6" }
fabric = "*"
grpcio = "1.27.2"
invoke = "*"
lxml = "*"
mako = "*"
netaddr = "*"
pillow = "*"
protobuf = "*"
pyproj = "*"
pyyaml = "*"

[tool.poetry.dev-dependencies]
black = "==19.3b0"
flake8 = "*"
grpcio-tools = "1.27.2"
isort = "*"
mock = "*"
pre-commit = "*"
pytest = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

